language: php

php:
  - 5.6
  - 7.0

env:
  - TYPO3_VERSION=^7.6
  - TYPO3_VERSION=~8.4.0
  - TYPO3_VERSION=~8.5.0

sudo: false

matrix:
  fast_finish: true
  exclude:
    - php: 5.6
      env: TYPO3_VERSION=~8.4.0
    - php: 5.6
      env: TYPO3_VERSION=~8.5.0

cache:
  apt: true
  directories:
    - $HOME/.composer/cache

before_install:
  - echo $TRAVIS_PHP_VERSION
  - if php -i | grep -q xdebug; then phpenv config-rm xdebug.ini; fi
  - composer self-update
  - composer --version
  - wget https://raw.github.com/lehmannro/assert.sh/v1.1/assert.sh -O .travis/assert.sh

before_script:
  - .travis/setup-typo3.sh $TYPO3_VERSION

addons:
  apt:
    packages:
      - nginx-extras
      - realpath
      - parallel

notifications:
  email:
    - bfr@qbus.de

install:
  #- composer install
  - .travis/install-nginx.sh

script:
  - >
    echo;
    echo "Running php lint";
    find . -name \*.php ! -path "./.Build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;

  - curl -vs 'http://localhost:8088/' &> /dev/stdout
  - curl -vs 'http://localhost:8088/' &> /dev/stdout
  - export HOST='http://localhost:8088'
  - .travis/run-tests.sh
  #- echo "<?php phpinfo();" > .Build/Web/info.php
  #- curl -vs 'http://localhost:8088/info.php' &> /dev/stdout
  - cat /tmp/error.log
  - cat /tmp/access.log
