language: php

sudo: false

env:
  - TYPO3_EXTRA_DEPENDENCIES=

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: TYPO3_VERSION=typo3/cms:~7.6.0
    - php: 7.0
      env: TYPO3_VERSION=typo3/cms:~7.6.0
    - php: 7.0
      env: TYPO3_VERSION=typo3/cms:~8.5.0
    - php: 7.0
      env: TYPO3_VERSION=typo3/cms:~8.6.0
    - php: 7.0
      env: TYPO3_VERSION=typo3/cms:~8.7.0
    - php: 7.1
      env: TYPO3_VERSION=typo3/cms:~8.7.0
    - php: 7.2
      env:
        - TYPO3_VERSION=typo3/minimal:^9.5
        - TYPO3_EXTRA_DEPENDENCIES=typo3/cms-adminpanel:^9.5

cache:
  apt: true
  directories:
    - $HOME/.composer/cache

before_install:
  - echo $TRAVIS_PHP_VERSION
  - if php -i | grep -q xdebug; then phpenv config-rm xdebug.ini; fi
  - composer self-update
  - composer --version
  - wget https://raw.github.com/lehmannro/assert.sh/v1.1/assert.sh -O .travis/assert.sh

before_script:
  - .travis/setup-typo3.sh $TYPO3_VERSION $TYPO3_EXTRA_DEPENDENCIES

addons:
  apt:
    packages:
      - nginx-extras
      - realpath
      - parallel

notifications:
  email:
    - bfr@qbus.de

install:
  #- composer install
  - sed -i -e 's/\[::1\]:80/[::]:80/' .travis/default-site.tpl.conf
  - .travis/install-nginx.sh

script:
  - >
    echo;
    echo "Running php lint";
    find . -name \*.php ! -path "./.Build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;

  - curl -vs 'http://localhost:8088/' &> /dev/stdout
  - curl -vs 'http://localhost:8088/' &> /dev/stdout
  - export HOST='http://localhost:8088'
  - .travis/run-tests.sh
  #- echo "<?php phpinfo();" > .Build/Web/info.php
  #- curl -vs 'http://localhost:8088/info.php' &> /dev/stdout
  - cat /tmp/error.log
  - cat /tmp/access.log
